# Generated by Django 4.2.6 on 2023-12-13 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Amazone", "0002_categeory"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categeory",
            new_name="Category",
        ),
    ]
